const readline = require('readline');
const bcrypt = require('bcryptjs');
const fs = require('fs');
const path = require('path');

const rl = readline.createInterface({
    input: process.stdin,
    output: process.stdout
});

const question = (query) => new Promise((resolve) => rl.question(query, resolve));

async function setup() {
    console.log('\n--- Hotware Dashboard Setup ---\n');

    try {
        // 1. Inputs
        const cloudEmail = await question('Enter Nx Cloud Email: ');
        const cloudPassword = await question('Enter Nx Cloud Password: ');
        const vmsUsername = await question('Enter VMS Local Admin Username: ');
        const vmsPassword = await question('Enter VMS Local Admin Password: ');

        console.log('\nValidating credentials...\n');

        // 2. Validate Cloud Credentials and get Token
        const cloudLoginUrl = 'https://meta.nxvms.com/cdb/login/sessions';
        const cloudResponse = await fetch(cloudLoginUrl, {
            method: 'POST',
            headers: { 'Content-Type': 'application/json' },
            body: JSON.stringify({ email: cloudEmail, password: cloudPassword })
        });

        if (!cloudResponse.ok) {
            const error = await cloudResponse.text();
            throw new Error(`Cloud Authentication Failed: ${cloudResponse.status} ${error}`);
        }

        const cloudData = await cloudResponse.json();
        const cloudToken = cloudData.token || cloudData.sid;

        if (!cloudToken) {
            throw new Error('Cloud login succeeded but no token was returned.');
        }

        console.log('✅ Nx Cloud Authentication Successful.');

        // 3. Fetch Systems from Cloud
        console.log('Fetching systems associated with your cloud account...');
        const systemsUrl = 'https://meta.nxvms.com/cdb/systems';
        const systemsResponse = await fetch(systemsUrl, {
            headers: { 'Authorization': `Bearer ${cloudToken}` }
        });

        if (!systemsResponse.ok) {
            throw new Error(`Failed to fetch systems: ${systemsResponse.status}`);
        }

        const systems = await systemsResponse.json();
        if (!Array.isArray(systems) || systems.length === 0) {
            throw new Error('No systems found in your Nx Cloud account.');
        }

        let systemId = '';
        if (systems.length === 1) {
            systemId = systems[0].id;
            console.log(`✅ Found System: ${systems[0].name} (${systemId})`);
        } else {
            console.log('\nMultiple systems found:');
            systems.forEach((s, i) => console.log(`${i + 1}. ${s.name} (${s.id})`));
            const choice = await question(`Select a system (1-${systems.length}): `);
            const index = parseInt(choice) - 1;
            if (index >= 0 && index < systems.length) {
                systemId = systems[index].id;
            } else {
                throw new Error('Invalid selection.');
            }
        }

        // 4. Validate System Accessibility via Relay (Double check)
        console.log(`Checking access to System ${systemId}...`);
        const relayUrl = `https://${systemId}.relay.vmsproxy.com/rest/v3/system/info`;
        const relayResponse = await fetch(relayUrl, {
            headers: { 'Authorization': `Bearer ${cloudToken}` }
        });

        if (!relayResponse.ok) {
            throw new Error(`System Accessibility Check Failed: ${relayResponse.status}. Check System ID and owner permissions.`);
        }

        console.log('✅ System Accessibility Verified.');

        // 4. Hash Local Password
        console.log('Hashing local password...');
        const salt = await bcrypt.genSalt(10);
        const hashedPassword = await bcrypt.hash(vmsPassword, salt);

        // 5. Generate config
        const envContent = [
            `# Generated by setup script on ${new Date().toISOString()}`,
            `NEXT_PUBLIC_NX_SYSTEM_ID=${systemId}`,
            `NEXT_PUBLIC_NX_USERNAME=${vmsUsername}`,
            `NX_ADMIN_HASH=${hashedPassword}`,
            `NX_CLOUD_TOKEN=${cloudToken}`,
            `# Note: Cloud credentials were used to generate the token and are NOT stored.`,
            ''
        ].join('\n');

        const envPath = path.join(process.cwd(), '.env.local');
        fs.writeFileSync(envPath, envContent, { flag: 'w' });

        console.log(`\n✅ Configuration saved to ${envPath}`);

        console.log('\n--- VERCEL / PRODUCTION CONFIG ---');
        console.log('Copy these variables to your Vercel Dashboard -> Settings -> Environment Variables:');
        console.log('');
        console.log(envContent.trim());
        console.log('----------------------------------\n');

        console.log('SUMMARY:');
        console.log(`- System ID: ${systemId}`);
        console.log(`- Admin User: ${vmsUsername}`);
        console.log(`- Password: [HASHED]`);
        console.log(`- Cloud Session: [TOKEN GENERATED]`);

        console.log('\nNext steps:');
        console.log('1. Run "npm run dev" to start the dashboard.');
        console.log('2. When prompted for password on the dashboard, use the VMS Local Admin Password.\n');

    } catch (error) {
        console.error('\n❌ ERROR:', error.message);
    } finally {
        rl.close();
    }
}

setup();
